package com.example.datban.model

// FoodItem.kt
data class FoodItem(
    val id: String = "", // Will be auto-generated by Firebase
    val name: String = "",
    val price: Double = 0.0,
    val imageUrl: String = "",
    val quantity: Int = 0,
    val type: String = "" // "buffet" or "a_la_carte"
)